// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTracker.Core.Storage;

#nullable disable

namespace TimeTracker.Core.Migrations
{
    [DbContext(typeof(TimeTrackerDbContext))]
    [Migration("20260709204602_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TimeTracker.Core.Storage.Entities.ActivitySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutableName")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIdle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowTitle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("StartedAtUtc", "ProcessName");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Core.Storage.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Core.Storage.Entities.CategoryRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(100);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "IsEnabled");

                    b.ToTable("category_rules", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Core.Storage.Entities.ActivitySession", b =>
                {
                    b.HasOne("TimeTracker.Core.Storage.Entities.Category", "Category")
                        .WithMany("Sessions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TimeTracker.Core.Storage.Entities.CategoryRule", b =>
                {
                    b.HasOne("TimeTracker.Core.Storage.Entities.Category", "Category")
                        .WithMany("Rules")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TimeTracker.Core.Storage.Entities.Category", b =>
                {
                    b.Navigation("Rules");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
